languageCode = "pt-br"
languageName = "PortuguÃªs"
weight = 1
title = "Blog do Leco"

[params]
  displayName = "PT-BR"
  isoCode = "pt-br"
  dateFormat = "2 January 2006"

  [params.author]
    name = "Leco"
    # image = "img/author.jpg"
    headline = "Desenvolvedor"
    bio = "Apaixonado por tecnologia e desenvolvimento de software"
    links = [
      { github = "https://github.com/l3co" },
      { linkedin = "https://linkedin.com/in/l3co" },
    ]
