[[main]]
  name = "Blog"
  pageRef = "posts"
  weight = 10

[[main]]
  name = "Tags"
  pageRef = "tags"
  weight = 20

[[main]]
  name = "Sobre"
  pageRef = "about"
  weight = 30

[[main]]
  pre = "github"
  identifier = "github"
  url = "https://github.com/l3co"
  weight = 40
