[[main]]
  name = "Blog"
  pageRef = "posts"
  weight = 10

[[main]]
  name = "Tags"
  pageRef = "tags"
  weight = 20

[[main]]
  pre = "github"
  name = "GitHub"
  url = "https://github.com/l3co"
  weight = 30
