colorScheme = "blowfish"
defaultAppearance = "dark"
autoSwitchAppearance = true
enableSearch = true
enableCodeCopy = true

[header]
  layout = "basic"

[footer]
  showMenu = true
  showCopyright = true
  showThemeAttribution = true
  showAppearanceSwitcher = true
  showScrollToTop = true

[homepage]
  layout = "profile"
  homepageImage = ""
  showRecent = true
  showRecentItems = 5
  showMoreLink = true
  showMoreLinkDest = "/posts"
  cardView = true
  cardViewScreenWidth = false
  layoutBackgroundBlur = true

[article]
  showDate = true
  showViews = false
  showLikes = false
  showDateUpdated = false
  showAuthor = true
  showBreadcrumbs = true
  showDraftLabel = true
  showEdit = false
  showHeadingAnchors = true
  showPagination = true
  showReadingTime = true
  showTableOfContents = true
  showTaxonomies = true
  showWordCount = false
  showSummary = true
  sharingLinks = ["facebook", "x-twitter", "linkedin", "reddit", "whatsapp", "telegram"]

[list]
  showBreadcrumbs = false
  showSummary = true
  showTableOfContents = false
  groupByYear = true
  cardView = true

[taxonomy]
  showTermCount = true
  cardView = false
