baseURL = 'https://l3co.github.io/'
title = 'Leco'
theme = 'hugo-brewm'
languageCode = 'pt-br'
enableRobotsTXT = true
enableGitInfo = true
canonifyURLs = false

[pagination]
  pagerSize = 10

[markup]
  [markup.highlight]
    codeFences = true
    noClasses = false

[taxonomies]
  tag = 'tags'

[params]
  title = "Leco"
  description = "Apaixonado por tecnologia e desenvolvimento de software"
  copyright = "Copyright 2025 Â© Leco"
  HideHugoCredit = false
  ZenMode = false

[params.author]
  name = 'Leco'

[params.feed]
  flowlines = true
  flowlinesLimit = 21

[params.home]
  disableSlide = true
  disableListing = false

[params.posts]
  justifying = false
  colophon = true
  related = true
  share = true

[params.typeface]
  webSafe = false
  roman = 'crimson'
  sans = 'inter'

[params.search]
  enable = false

[[menus.main]]
  name = "Posts"
  pageRef = "/post"
  weight = 10

[[menus.main]]
  name = "Tags"
  pageRef = "/tags"
  weight = 20

[[menus.main]]
  name = "Sobre"
  pageRef = "/about"
  weight = 30
