baseURL = "https://l3co.github.io/"
title = "Leco"
languageCode = "pt-br"
enableRobotsTXT = true
enableGitInfo = true

[pagination]
  pagerSize = 10

[params]
  description = "Apaixonado por tecnologia e desenvolvimento de software"
  author = "Leco"

[params.home]
  sections = ["posts"]
  fullCover = false
  centerHeadline = false

[params.sections]
  [params.sections.posts]
    title = "Posts Recentes"
    sort = "date"
    reverse = true
    cols = 3
    padding = "0"
    header = "full"
    footer = "tags"
    orientation = "stacked"
    style = "border-0 card-zoom card-body-margin"
    homepage = 6
    separator = true

[params.navigation]
  logo = "img/logo.png"
  logo-mode = false
  logo-height = 30
  color = "body"
  fixed = true

[params.favicon]
  logo = "img/favicon.png"
  sizes = [16, 32, 48]

[params.style]
  primary = "#059669"
  themeOpacity = "O-75"
  
[outputs]
  home = ["HTML", "RSS"]

[markup]
  [markup.highlight]
    noClasses = false

[[menus.main]]
  name = "Posts"
  pageRef = "/posts"
  weight = 10

[[menus.main]]
  name = "Tags"
  pageRef = "/tags"
  weight = 20

[[menus.main]]
  name = "Sobre"
  pageRef = "/about"
  weight = 30

[[module.imports]]
  path = "github.com/gethinode/hinode"
