baseURL = "https://l3co.github.io/"
title = "Leco"
languageCode = "pt-br"
enableRobotsTXT = true
enableGitInfo = true

[pagination]
  pagerSize = 10

[params]
  description = "Apaixonado por tecnologia e desenvolvimento de software"
  author = "Leco"

[params.style]
  themeOpacity = "O-75"
  
[outputs]
  home = ["HTML", "RSS"]

[markup]
  [markup.highlight]
    noClasses = false

[[menus.main]]
  name = "Posts"
  pageRef = "/posts"
  weight = 10

[[menus.main]]
  name = "Tags"
  pageRef = "/tags"
  weight = 20

[[menus.main]]
  name = "Sobre"
  pageRef = "/about"
  weight = 30

[[module.imports]]
  path = "github.com/gethinode/hinode"
